/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Basket {
  'id' : bigint,
  'rebalanceThresholdBps' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'riskTier' : string,
  'description' : string,
  'slots' : Array<BasketSlot>,
  'updatedAt' : bigint,
}
export interface BasketSlot {
  'slotLabel' : string,
  'targetWeightBps' : bigint,
  'pairTradeId' : bigint,
}
export interface FundingEntry {
  'id' : bigint,
  'entryType' : FundingEntryType,
  'note' : string,
  'timestamp' : bigint,
  'amountICP' : number,
}
export type FundingEntryType = { 'deposit' : null } |
  { 'stakingReward' : null };
export interface Holding {
  'balance' : number,
  'tokenCanisterId' : string,
  'costBasis' : number,
  'symbol' : string,
}
export interface PairTrade {
  'id' : bigint,
  'allocationUsd' : number,
  'createdAt' : bigint,
  'riskTier' : RiskTier,
  'tokenAAddress' : string,
  'tokenASymbol' : string,
  'routeViaICP' : boolean,
  'notes' : string,
  'tokenBAddress' : string,
  'tokenBSymbol' : string,
}
export type RiskTier = { 'conservative' : null } |
  { 'aggressive' : null } |
  { 'moderate' : null };
export interface SwapReceipt {
  'id' : string,
  'tokenIn' : string,
  'tokenOut' : string,
  'amountIn' : number,
  'realizedPnL' : number,
  'timestamp' : bigint,
  'priceImpactPct' : number,
  'amountOut' : number,
  'route' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'riskPreference' : string,
  'displayName' : string,
  'preferredCurrency' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFundingEntry' : ActorMethod<[FundingEntryType, number, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBasket' : ActorMethod<
    [string, string, Array<BasketSlot>, bigint],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'createPairTrade' : ActorMethod<
    [string, string, string, string, number, RiskTier, boolean, string],
    bigint
  >,
  'deleteBasket' : ActorMethod<[bigint], boolean>,
  'deletePairTrade' : ActorMethod<[bigint], boolean>,
  'executeSwap' : ActorMethod<
    [Principal, number, Principal, string, number],
    string
  >,
  'fetchDexScreenerPairs' : ActorMethod<[], string>,
  'fetchICPSwapTokens' : ActorMethod<[], string>,
  'fetchKongSwapTokens' : ActorMethod<[], string>,
  'getAvailableICPBalance' : ActorMethod<[], number>,
  'getBasket' : ActorMethod<[bigint], [] | [Basket]>,
  'getBasketDrift' : ActorMethod<
    [bigint, Array<[string, number]>],
    Array<{ 'direction' : string, 'slotIndex' : bigint, 'driftBps' : bigint }>
  >,
  'getBasketRiskTier' : ActorMethod<[bigint], [] | [string]>,
  'getBaskets' : ActorMethod<[], Array<Basket>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDecimals' : ActorMethod<[Principal], number>,
  'getFundingEntries' : ActorMethod<[], Array<FundingEntry>>,
  'getHolding' : ActorMethod<[string], [] | [Holding]>,
  'getHoldings' : ActorMethod<[], Array<Holding>>,
  'getPairTrade' : ActorMethod<[bigint], [] | [PairTrade]>,
  'getPairTrades' : ActorMethod<[], Array<PairTrade>>,
  'getPortfolioValue' : ActorMethod<[Array<[string, number]>], number>,
  'getProfile' : ActorMethod<
    [],
    {
        'ok' : {
          'riskPreference' : string,
          'displayName' : string,
          'preferredCurrency' : string,
          'ownerPrincipal' : [] | [Principal],
        }
      } |
      { 'err' : string }
  >,
  'getSwapQuote' : ActorMethod<[string, number, string], number>,
  'getSwapReceipts' : ActorMethod<[], Array<SwapReceipt>>,
  'getTotalFundedICP' : ActorMethod<[], number>,
  'getTotalRealizedPnL' : ActorMethod<[], number>,
  'getTradeFrequencyCap' : ActorMethod<[RiskTier], bigint>,
  'getTradeFrequencyStatus' : ActorMethod<
    [],
    {
      'resetsAt' : bigint,
      'usedThisMonth' : bigint,
      'pctUsed' : bigint,
      'limitThisMonth' : bigint,
    }
  >,
  'getTradingPermissionExpiry' : ActorMethod<[], [] | [bigint]>,
  'getUnrealizedPnL' : ActorMethod<[Array<[string, number]>, number], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantTradingPermission' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'revokeTradingPermission' : ActorMethod<[], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDecimals' : ActorMethod<[Principal, number], undefined>,
  'setProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBasket' : ActorMethod<
    [bigint, string, string, Array<BasketSlot>, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateHolding' : ActorMethod<[string, number], undefined>,
  'updatePairTrade' : ActorMethod<[bigint, number, RiskTier, string], boolean>,
  'validateBasketSlots' : ActorMethod<
    [Array<BasketSlot>],
    { 'valid' : boolean, 'error' : [] | [string] }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];