/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FundingEntryType = IDL.Variant({
  'deposit' : IDL.Null,
  'stakingReward' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BasketSlot = IDL.Record({
  'slotLabel' : IDL.Text,
  'targetWeightBps' : IDL.Nat,
  'pairTradeId' : IDL.Nat,
});
export const RiskTier = IDL.Variant({
  'conservative' : IDL.Null,
  'aggressive' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Basket = IDL.Record({
  'id' : IDL.Nat,
  'rebalanceThresholdBps' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'riskTier' : IDL.Text,
  'description' : IDL.Text,
  'slots' : IDL.Vec(BasketSlot),
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'riskPreference' : IDL.Text,
  'displayName' : IDL.Text,
  'preferredCurrency' : IDL.Text,
});
export const FundingEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : FundingEntryType,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'amountICP' : IDL.Float64,
});
export const Holding = IDL.Record({
  'balance' : IDL.Float64,
  'tokenCanisterId' : IDL.Text,
  'costBasis' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PairTrade = IDL.Record({
  'id' : IDL.Nat,
  'allocationUsd' : IDL.Float64,
  'createdAt' : IDL.Int,
  'riskTier' : RiskTier,
  'tokenAAddress' : IDL.Text,
  'tokenASymbol' : IDL.Text,
  'routeViaICP' : IDL.Bool,
  'notes' : IDL.Text,
  'tokenBAddress' : IDL.Text,
  'tokenBSymbol' : IDL.Text,
});
export const SwapReceipt = IDL.Record({
  'id' : IDL.Text,
  'tokenIn' : IDL.Text,
  'tokenOut' : IDL.Text,
  'amountIn' : IDL.Float64,
  'realizedPnL' : IDL.Float64,
  'timestamp' : IDL.Int,
  'priceImpactPct' : IDL.Float64,
  'amountOut' : IDL.Float64,
  'route' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFundingEntry' : IDL.Func(
      [FundingEntryType, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBasket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(BasketSlot), IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'createPairTrade' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        RiskTier,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteBasket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePairTrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'executeSwap' : IDL.Func(
      [IDL.Principal, IDL.Float64, IDL.Principal, IDL.Text, IDL.Float64],
      [IDL.Text],
      [],
    ),
  'fetchDexScreenerPairs' : IDL.Func([], [IDL.Text], []),
  'fetchICPSwapTokens' : IDL.Func([], [IDL.Text], []),
  'fetchKongSwapTokens' : IDL.Func([], [IDL.Text], []),
  'getAvailableICPBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getBasket' : IDL.Func([IDL.Nat], [IDL.Opt(Basket)], ['query']),
  'getBasketDrift' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [
        IDL.Vec(
          IDL.Record({
            'direction' : IDL.Text,
            'slotIndex' : IDL.Nat,
            'driftBps' : IDL.Int,
          })
        ),
      ],
      [],
    ),
  'getBasketRiskTier' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], []),
  'getBaskets' : IDL.Func([], [IDL.Vec(Basket)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDecimals' : IDL.Func([IDL.Principal], [IDL.Nat8], ['query']),
  'getFundingEntries' : IDL.Func([], [IDL.Vec(FundingEntry)], ['query']),
  'getHolding' : IDL.Func([IDL.Text], [IDL.Opt(Holding)], ['query']),
  'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getPairTrade' : IDL.Func([IDL.Nat], [IDL.Opt(PairTrade)], ['query']),
  'getPairTrades' : IDL.Func([], [IDL.Vec(PairTrade)], ['query']),
  'getPortfolioValue' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [IDL.Float64],
      [],
    ),
  'getProfile' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'riskPreference' : IDL.Text,
            'displayName' : IDL.Text,
            'preferredCurrency' : IDL.Text,
            'ownerPrincipal' : IDL.Opt(IDL.Principal),
          }),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getSwapQuote' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Float64],
      [],
    ),
  'getSwapReceipts' : IDL.Func([], [IDL.Vec(SwapReceipt)], ['query']),
  'getTotalFundedICP' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalRealizedPnL' : IDL.Func([], [IDL.Float64], ['query']),
  'getTradeFrequencyCap' : IDL.Func([RiskTier], [IDL.Nat], ['query']),
  'getTradeFrequencyStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'resetsAt' : IDL.Int,
          'usedThisMonth' : IDL.Nat,
          'pctUsed' : IDL.Nat,
          'limitThisMonth' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTradingPermissionExpiry' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getUnrealizedPnL' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)), IDL.Float64],
      [IDL.Float64],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantTradingPermission' : IDL.Func([], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeTradingPermission' : IDL.Func([], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDecimals' : IDL.Func([IDL.Principal, IDL.Nat8], [], []),
  'setProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBasket' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(BasketSlot), IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateHolding' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updatePairTrade' : IDL.Func(
      [IDL.Nat, IDL.Float64, RiskTier, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'validateBasketSlots' : IDL.Func(
      [IDL.Vec(BasketSlot)],
      [IDL.Record({ 'valid' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
      ['query'],
    ),
  'analyzeAndDecide' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Float64, IDL.Text], [IDL.Text], []),
  'depositBtc' : IDL.Func([], [IDL.Text], []),
  'depositEth' : IDL.Func([], [IDL.Text], []),
  'getBasketFocusAsset' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getBtcDepositAddress' : IDL.Func([], [IDL.Text], []),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getEthDepositAddress' : IDL.Func([], [IDL.Text], []),
  'getHardcodedTokens' : IDL.Func([], [IDL.Text], ['query']),
  'getPortfolioHistory' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Record({ 'timestamp' : IDL.Int, 'valueUsd' : IDL.Float64 }))], ['query']),
  'getUniqueDepositAddress' : IDL.Func([], [IDL.Text], ['query']),
  'requireIIVerification' : IDL.Func([], [IDL.Bool], ['query']),
  'syncBalances' : IDL.Func([], [IDL.Text], []),
  'toggleAgent' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [IDL.Bool], []),
  'updateScalpingMode' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'withdrawWithDenomination' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text, IDL.Principal], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FundingEntryType = IDL.Variant({
    'deposit' : IDL.Null,
    'stakingReward' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BasketSlot = IDL.Record({
    'slotLabel' : IDL.Text,
    'targetWeightBps' : IDL.Nat,
    'pairTradeId' : IDL.Nat,
  });
  const RiskTier = IDL.Variant({
    'conservative' : IDL.Null,
    'aggressive' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Basket = IDL.Record({
    'id' : IDL.Nat,
    'rebalanceThresholdBps' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'riskTier' : IDL.Text,
    'description' : IDL.Text,
    'slots' : IDL.Vec(BasketSlot),
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'riskPreference' : IDL.Text,
    'displayName' : IDL.Text,
    'preferredCurrency' : IDL.Text,
  });
  const FundingEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : FundingEntryType,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'amountICP' : IDL.Float64,
  });
  const Holding = IDL.Record({
    'balance' : IDL.Float64,
    'tokenCanisterId' : IDL.Text,
    'costBasis' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PairTrade = IDL.Record({
    'id' : IDL.Nat,
    'allocationUsd' : IDL.Float64,
    'createdAt' : IDL.Int,
    'riskTier' : RiskTier,
    'tokenAAddress' : IDL.Text,
    'tokenASymbol' : IDL.Text,
    'routeViaICP' : IDL.Bool,
    'notes' : IDL.Text,
    'tokenBAddress' : IDL.Text,
    'tokenBSymbol' : IDL.Text,
  });
  const SwapReceipt = IDL.Record({
    'id' : IDL.Text,
    'tokenIn' : IDL.Text,
    'tokenOut' : IDL.Text,
    'amountIn' : IDL.Float64,
    'realizedPnL' : IDL.Float64,
    'timestamp' : IDL.Int,
    'priceImpactPct' : IDL.Float64,
    'amountOut' : IDL.Float64,
    'route' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFundingEntry' : IDL.Func(
        [FundingEntryType, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBasket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(BasketSlot), IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'createPairTrade' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          RiskTier,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBasket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePairTrade' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'executeSwap' : IDL.Func(
        [IDL.Principal, IDL.Float64, IDL.Principal, IDL.Text, IDL.Float64],
        [IDL.Text],
        [],
      ),
    'fetchDexScreenerPairs' : IDL.Func([], [IDL.Text], []),
    'fetchICPSwapTokens' : IDL.Func([], [IDL.Text], []),
    'fetchKongSwapTokens' : IDL.Func([], [IDL.Text], []),
    'getAvailableICPBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getBasket' : IDL.Func([IDL.Nat], [IDL.Opt(Basket)], ['query']),
    'getBasketDrift' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [
          IDL.Vec(
            IDL.Record({
              'direction' : IDL.Text,
              'slotIndex' : IDL.Nat,
              'driftBps' : IDL.Int,
            })
          ),
        ],
        [],
      ),
    'getBasketRiskTier' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], []),
    'getBaskets' : IDL.Func([], [IDL.Vec(Basket)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDecimals' : IDL.Func([IDL.Principal], [IDL.Nat8], ['query']),
    'getFundingEntries' : IDL.Func([], [IDL.Vec(FundingEntry)], ['query']),
    'getHolding' : IDL.Func([IDL.Text], [IDL.Opt(Holding)], ['query']),
    'getHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getPairTrade' : IDL.Func([IDL.Nat], [IDL.Opt(PairTrade)], ['query']),
    'getPairTrades' : IDL.Func([], [IDL.Vec(PairTrade)], ['query']),
    'getPortfolioValue' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [IDL.Float64],
        [],
      ),
    'getProfile' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'riskPreference' : IDL.Text,
              'displayName' : IDL.Text,
              'preferredCurrency' : IDL.Text,
              'ownerPrincipal' : IDL.Opt(IDL.Principal),
            }),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getSwapQuote' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Float64],
        [],
      ),
    'getSwapReceipts' : IDL.Func([], [IDL.Vec(SwapReceipt)], ['query']),
    'getTotalFundedICP' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalRealizedPnL' : IDL.Func([], [IDL.Float64], ['query']),
    'getTradeFrequencyCap' : IDL.Func([RiskTier], [IDL.Nat], ['query']),
    'getTradeFrequencyStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'resetsAt' : IDL.Int,
            'usedThisMonth' : IDL.Nat,
            'pctUsed' : IDL.Nat,
            'limitThisMonth' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTradingPermissionExpiry' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getUnrealizedPnL' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)), IDL.Float64],
        [IDL.Float64],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantTradingPermission' : IDL.Func([], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeTradingPermission' : IDL.Func([], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDecimals' : IDL.Func([IDL.Principal, IDL.Nat8], [], []),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBasket' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(BasketSlot), IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateHolding' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updatePairTrade' : IDL.Func(
        [IDL.Nat, IDL.Float64, RiskTier, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'validateBasketSlots' : IDL.Func(
        [IDL.Vec(BasketSlot)],
        [IDL.Record({ 'valid' : IDL.Bool, 'error' : IDL.Opt(IDL.Text) })],
        ['query'],
      ),
    'analyzeAndDecide' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Float64, IDL.Text], [IDL.Text], []),
    'depositBtc' : IDL.Func([], [IDL.Text], []),
    'depositEth' : IDL.Func([], [IDL.Text], []),
    'getBasketFocusAsset' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getBtcDepositAddress' : IDL.Func([], [IDL.Text], []),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getEthDepositAddress' : IDL.Func([], [IDL.Text], []),
    'getHardcodedTokens' : IDL.Func([], [IDL.Text], ['query']),
    'getPortfolioHistory' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Record({ 'timestamp' : IDL.Int, 'valueUsd' : IDL.Float64 }))], ['query']),
    'getUniqueDepositAddress' : IDL.Func([], [IDL.Text], ['query']),
    'requireIIVerification' : IDL.Func([], [IDL.Bool], ['query']),
    'syncBalances' : IDL.Func([], [IDL.Text], []),
    'toggleAgent' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Bool], [IDL.Bool], []),
    'updateScalpingMode' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'withdrawWithDenomination' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text, IDL.Principal], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };