/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PairTrade {
    id: bigint;
    allocationUsd: number;
    createdAt: bigint;
    riskTier: RiskTier;
    tokenAAddress: string;
    tokenASymbol: string;
    routeViaICP: boolean;
    notes: string;
    tokenBAddress: string;
    tokenBSymbol: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FundingEntry {
    id: bigint;
    entryType: FundingEntryType;
    note: string;
    timestamp: bigint;
    amountICP: number;
}
export interface SwapReceipt {
    id: string;
    tokenIn: string;
    tokenOut: string;
    amountIn: number;
    realizedPnL: number;
    timestamp: bigint;
    priceImpactPct: number;
    amountOut: number;
    route: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BasketSlot {
    slotLabel: string;
    targetWeightBps: bigint;
    pairTradeId: bigint;
}
export interface Holding {
    balance: number;
    tokenCanisterId: string;
    costBasis: number;
    symbol: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Basket {
    id: bigint;
    rebalanceThresholdBps: bigint;
    name: string;
    createdAt: bigint;
    riskTier: string;
    description: string;
    slots: Array<BasketSlot>;
    updatedAt: bigint;
}
export interface UserProfile {
    riskPreference: string;
    displayName: string;
    preferredCurrency: string;
}
export enum FundingEntryType {
    deposit = "deposit",
    stakingReward = "stakingReward"
}
export enum RiskTier {
    conservative = "conservative",
    aggressive = "aggressive",
    moderate = "moderate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFundingEntry(entryType: FundingEntryType, amountICP: number, note: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBasket(name: string, description: string, slots: Array<BasketSlot>, rebalanceThresholdBps: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPairTrade(tokenAAddress: string, tokenASymbol: string, tokenBAddress: string, tokenBSymbol: string, allocationUsd: number, riskTier: RiskTier, routeViaICP: boolean, notes: string): Promise<bigint>;
    deleteBasket(id: bigint): Promise<boolean>;
    deletePairTrade(id: bigint): Promise<boolean>;
    executeSwap(tokenIn: Principal, amountIn: number, tokenOut: Principal, route: string, priceImpactPct: number): Promise<string>;
    fetchDexScreenerPairs(): Promise<string>;
    fetchICPSwapTokens(): Promise<string>;
    fetchKongSwapTokens(): Promise<string>;
    getTokenUniverseCaches(): Promise<{ dexScreener: string; icpSwap: string; kongSwap: string; updatedAt: bigint }>;
    updateTokenUniverse(): Promise<void>;
    getAvailableICPBalance(): Promise<number>;
    getBasket(id: bigint): Promise<Basket | null>;
    getBasketDrift(basketId: bigint, priceMap: Array<[string, number]>): Promise<Array<{
        direction: string;
        slotIndex: bigint;
        driftBps: bigint;
    }>>;
    getBasketRiskTier(id: bigint): Promise<string | null>;
    getBaskets(): Promise<Array<Basket>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDecimals(token: Principal): Promise<number>;
    getFundingEntries(): Promise<Array<FundingEntry>>;
    getHolding(tokenCanisterId: string): Promise<Holding | null>;
    getHoldings(): Promise<Array<Holding>>;
    getPairTrade(id: bigint): Promise<PairTrade | null>;
    getPairTrades(): Promise<Array<PairTrade>>;
    getPortfolioValue(priceMap: Array<[string, number]>): Promise<number>;
    getProfile(): Promise<{
        __kind__: "ok";
        ok: {
            riskPreference: string;
            displayName: string;
            preferredCurrency: string;
            ownerPrincipal?: Principal;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    getSwapQuote(tokenIn: string, amountIn: number, tokenOut: string): Promise<number>;
    getSwapReceipts(): Promise<Array<SwapReceipt>>;
    getTotalFundedICP(): Promise<number>;
    getTotalRealizedPnL(): Promise<number>;
    getTradeFrequencyCap(riskTier: RiskTier): Promise<bigint>;
    getTradeFrequencyStatus(): Promise<{
        resetsAt: bigint;
        usedThisMonth: bigint;
        pctUsed: bigint;
        limitThisMonth: bigint;
    }>;
    getTradingPermissionExpiry(): Promise<bigint | null>;
    getUnrealizedPnL(priceMap: Array<[string, number]>, icpPriceUsd: number): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantTradingPermission(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    isOwner(): Promise<boolean>;
    revokeTradingPermission(): Promise<string>;
    getUniqueDepositAddress(): Promise<string>;
    getBtcDepositAddress(): Promise<string>;
    getEthDepositAddress(): Promise<string>;
    depositBtc(): Promise<string>;
    depositEth(): Promise<string>;
    toggleAgent(id: bigint, isPairTrade: boolean, enabled: boolean): Promise<boolean>;
    analyzeAndDecide(id: bigint, isPairTrade: boolean, focusAssetPrice: number, indicatorSummary: string): Promise<string>;
    syncBalances(): Promise<string>;
    withdrawWithDenomination(tokenSymbol: string, amount: number, denomination: string, destination: Principal): Promise<string>;
    getPortfolioHistory(days: bigint): Promise<Array<{timestamp: bigint, valueUsd: number}>>;
    getBasketFocusAsset(id: bigint): Promise<string>;
    updateScalpingMode(id: bigint, enabled: boolean): Promise<boolean>;
    getHardcodedTokens(): Promise<string>;
    getCanisterId(): Promise<Principal>;
    requireIIVerification(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setDecimals(token: Principal, decimals: number): Promise<void>;
    setProfile(name: string, currency: string, risk: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBasket(id: bigint, name: string, description: string, slots: Array<BasketSlot>, rebalanceThresholdBps: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateHolding(tokenCanisterId: string, amountChange: number): Promise<void>;
    updatePairTrade(id: bigint, allocationUsd: number, riskTier: RiskTier, notes: string): Promise<boolean>;
    validateBasketSlots(slots: Array<BasketSlot>): Promise<{
        valid: boolean;
        error?: string;
    }>;
}
import type { Basket as _Basket, FundingEntry as _FundingEntry, FundingEntryType as _FundingEntryType, Holding as _Holding, PairTrade as _PairTrade, RiskTier as _RiskTier, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFundingEntry(arg0: FundingEntryType, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFundingEntry(to_candid_FundingEntryType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFundingEntry(to_candid_FundingEntryType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBasket(arg0: string, arg1: string, arg2: Array<BasketSlot>, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBasket(arg0, arg1, arg2, arg3);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBasket(arg0, arg1, arg2, arg3);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPairTrade(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: RiskTier, arg6: boolean, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPairTrade(arg0, arg1, arg2, arg3, arg4, to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPairTrade(arg0, arg1, arg2, arg3, arg4, to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async deleteBasket(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBasket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBasket(arg0);
            return result;
        }
    }
    async deletePairTrade(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePairTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePairTrade(arg0);
            return result;
        }
    }
    async executeSwap(arg0: Principal, arg1: number, arg2: Principal, arg3: string, arg4: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.executeSwap(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.executeSwap(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async fetchDexScreenerPairs(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDexScreenerPairs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDexScreenerPairs();
            return result;
        }
    }
    async fetchICPSwapTokens(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchICPSwapTokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchICPSwapTokens();
            return result;
        }
    }
    async fetchKongSwapTokens(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchKongSwapTokens();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchKongSwapTokens();
            return result;
        }
    }
    async getTokenUniverseCaches(): Promise<{ dexScreener: string; icpSwap: string; kongSwap: string; updatedAt: bigint }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenUniverseCaches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenUniverseCaches();
            return result;
        }
    }
    async updateTokenUniverse(): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateTokenUniverse();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.updateTokenUniverse();
        }
    }
    async getAvailableICPBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableICPBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableICPBalance();
            return result;
        }
    }
    async getBasket(arg0: bigint): Promise<Basket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBasket(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBasket(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBasketDrift(arg0: bigint, arg1: Array<[string, number]>): Promise<Array<{
        direction: string;
        slotIndex: bigint;
        driftBps: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBasketDrift(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBasketDrift(arg0, arg1);
            return result;
        }
    }
    async getBasketRiskTier(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBasketRiskTier(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBasketRiskTier(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBaskets(): Promise<Array<Basket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBaskets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBaskets();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDecimals(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDecimals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDecimals(arg0);
            return result;
        }
    }
    async getFundingEntries(): Promise<Array<FundingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFundingEntries();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFundingEntries();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolding(arg0: string): Promise<Holding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolding(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolding(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHoldings(): Promise<Array<Holding>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoldings();
            return result;
        }
    }
    async getPairTrade(arg0: bigint): Promise<PairTrade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairTrade(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairTrade(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairTrades(): Promise<Array<PairTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairTrades();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairTrades();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioValue(arg0: Array<[string, number]>): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioValue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioValue(arg0);
            return result;
        }
    }
    async getProfile(): Promise<{
        __kind__: "ok";
        ok: {
            riskPreference: string;
            displayName: string;
            preferredCurrency: string;
            ownerPrincipal?: Principal;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSwapQuote(arg0: string, arg1: number, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getSwapQuote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSwapQuote(arg0, arg1, arg2);
            return result;
        }
    }
    async getSwapReceipts(): Promise<Array<SwapReceipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSwapReceipts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSwapReceipts();
            return result;
        }
    }
    async getTotalFundedICP(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFundedICP();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFundedICP();
            return result;
        }
    }
    async getTotalRealizedPnL(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRealizedPnL();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRealizedPnL();
            return result;
        }
    }
    async getTradeFrequencyCap(arg0: RiskTier): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeFrequencyCap(to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeFrequencyCap(to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTradeFrequencyStatus(): Promise<{
        resetsAt: bigint;
        usedThisMonth: bigint;
        pctUsed: bigint;
        limitThisMonth: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeFrequencyStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeFrequencyStatus();
            return result;
        }
    }
    async getTradingPermissionExpiry(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradingPermissionExpiry();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradingPermissionExpiry();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnrealizedPnL(arg0: Array<[string, number]>, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnrealizedPnL(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnrealizedPnL(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantTradingPermission(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.grantTradingPermission();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantTradingPermission();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOwner(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOwner();
            return result;
        }
    }
    async revokeTradingPermission(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeTradingPermission();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeTradingPermission();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setDecimals(arg0: Principal, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDecimals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDecimals(arg0, arg1);
            return result;
        }
    }
    async setProfile(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1, arg2);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1, arg2);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBasket(arg0: bigint, arg1: string, arg2: string, arg3: Array<BasketSlot>, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBasket(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBasket(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHolding(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHolding(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHolding(arg0, arg1);
            return result;
        }
    }
    async updatePairTrade(arg0: bigint, arg1: number, arg2: RiskTier, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePairTrade(arg0, arg1, to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePairTrade(arg0, arg1, to_candid_RiskTier_n6(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async validateBasketSlots(arg0: Array<BasketSlot>): Promise<{
        valid: boolean;
        error?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBasketSlots(arg0);
                return from_candid_record_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBasketSlots(arg0);
            return from_candid_record_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUniqueDepositAddress(): Promise<string> {
        const result = await this.actor.getUniqueDepositAddress();
        return result;
    }
    async getBtcDepositAddress(): Promise<string> {
        const result = await this.actor.getBtcDepositAddress();
        return result;
    }
    async getEthDepositAddress(): Promise<string> {
        const result = await this.actor.getEthDepositAddress();
        return result;
    }
    async depositBtc(): Promise<string> {
        const result = await this.actor.depositBtc();
        return result;
    }
    async depositEth(): Promise<string> {
        const result = await this.actor.depositEth();
        return result;
    }
    async toggleAgent(id: bigint, isPairTrade: boolean, enabled: boolean): Promise<boolean> {
        const result = await this.actor.toggleAgent(id, isPairTrade, enabled);
        return result;
    }
    async analyzeAndDecide(id: bigint, isPairTrade: boolean, focusAssetPrice: number, indicatorSummary: string): Promise<string> {
        const result = await this.actor.analyzeAndDecide(id, isPairTrade, focusAssetPrice, indicatorSummary);
        return result;
    }
    async syncBalances(): Promise<string> {
        const result = await this.actor.syncBalances();
        return result;
    }
    async withdrawWithDenomination(tokenSymbol: string, amount: number, denomination: string, destination: Principal): Promise<string> {
        const result = await this.actor.withdrawWithDenomination(tokenSymbol, amount, denomination, destination);
        return result;
    }
    async getPortfolioHistory(days: bigint): Promise<Array<{timestamp: bigint, valueUsd: number}>> {
        const result = await this.actor.getPortfolioHistory(days);
        return result as Array<{timestamp: bigint, valueUsd: number}>;
    }
    async getBasketFocusAsset(id: bigint): Promise<string> {
        const result = await this.actor.getBasketFocusAsset(id);
        return result;
    }
    async updateScalpingMode(id: bigint, enabled: boolean): Promise<boolean> {
        const result = await this.actor.updateScalpingMode(id, enabled);
        return result;
    }
    async getHardcodedTokens(): Promise<string> {
        const result = await this.actor.getHardcodedTokens();
        return result;
    }
    async getCanisterId(): Promise<Principal> {
        const result = await this.actor.getCanisterId();
        return result;
    }
    async requireIIVerification(): Promise<boolean> {
        const result = await this.actor.requireIIVerification();
        return result;
    }
}
function from_candid_FundingEntryType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundingEntryType): FundingEntryType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FundingEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FundingEntry): FundingEntry {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PairTrade_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PairTrade): PairTrade {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_RiskTier_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskTier): RiskTier {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Holding]): Holding | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PairTrade]): PairTrade | null {
    return value.length === 0 ? null : from_candid_PairTrade_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Basket]): Basket | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    entryType: _FundingEntryType;
    note: string;
    timestamp: bigint;
    amountICP: number;
}): {
    id: bigint;
    entryType: FundingEntryType;
    note: string;
    timestamp: bigint;
    amountICP: number;
} {
    return {
        id: value.id,
        entryType: from_candid_FundingEntryType_n16(_uploadFile, _downloadFile, value.entryType),
        note: value.note,
        timestamp: value.timestamp,
        amountICP: value.amountICP
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    allocationUsd: number;
    createdAt: bigint;
    riskTier: _RiskTier;
    tokenAAddress: string;
    tokenASymbol: string;
    routeViaICP: boolean;
    notes: string;
    tokenBAddress: string;
    tokenBSymbol: string;
}): {
    id: bigint;
    allocationUsd: number;
    createdAt: bigint;
    riskTier: RiskTier;
    tokenAAddress: string;
    tokenASymbol: string;
    routeViaICP: boolean;
    notes: string;
    tokenBAddress: string;
    tokenBSymbol: string;
} {
    return {
        id: value.id,
        allocationUsd: value.allocationUsd,
        createdAt: value.createdAt,
        riskTier: from_candid_RiskTier_n22(_uploadFile, _downloadFile, value.riskTier),
        tokenAAddress: value.tokenAAddress,
        tokenASymbol: value.tokenASymbol,
        routeViaICP: value.routeViaICP,
        notes: value.notes,
        tokenBAddress: value.tokenBAddress,
        tokenBSymbol: value.tokenBSymbol
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskPreference: string;
    displayName: string;
    preferredCurrency: string;
    ownerPrincipal: [] | [Principal];
}): {
    riskPreference: string;
    displayName: string;
    preferredCurrency: string;
    ownerPrincipal?: Principal;
} {
    return {
        riskPreference: value.riskPreference,
        displayName: value.displayName,
        preferredCurrency: value.preferredCurrency,
        ownerPrincipal: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.ownerPrincipal))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    valid: boolean;
    error: [] | [string];
}): {
    valid: boolean;
    error?: string;
} {
    return {
        valid: value.valid,
        error: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.error))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit: null;
} | {
    stakingReward: null;
}): FundingEntryType {
    return "deposit" in value ? FundingEntryType.deposit : "stakingReward" in value ? FundingEntryType.stakingReward : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conservative: null;
} | {
    aggressive: null;
} | {
    moderate: null;
}): RiskTier {
    return "conservative" in value ? RiskTier.conservative : "aggressive" in value ? RiskTier.aggressive : "moderate" in value ? RiskTier.moderate : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        riskPreference: string;
        displayName: string;
        preferredCurrency: string;
        ownerPrincipal: [] | [Principal];
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        riskPreference: string;
        displayName: string;
        preferredCurrency: string;
        ownerPrincipal?: Principal;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FundingEntry>): Array<FundingEntry> {
    return value.map((x)=>from_candid_FundingEntry_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PairTrade>): Array<PairTrade> {
    return value.map((x)=>from_candid_PairTrade_n20(_uploadFile, _downloadFile, x));
}
function to_candid_FundingEntryType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundingEntryType): _FundingEntryType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RiskTier_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTier): _RiskTier {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FundingEntryType): {
    deposit: null;
} | {
    stakingReward: null;
} {
    return value == FundingEntryType.deposit ? {
        deposit: null
    } : value == FundingEntryType.stakingReward ? {
        stakingReward: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTier): {
    conservative: null;
} | {
    aggressive: null;
} | {
    moderate: null;
} {
    return value == RiskTier.conservative ? {
        conservative: null
    } : value == RiskTier.aggressive ? {
        aggressive: null
    } : value == RiskTier.moderate ? {
        moderate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
